# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# This file is the main configuration for the project environment. It includes
# the engine and app settings for all integrations running in this context.

includes:
  - ./includes/substancepainter/project.yml

engines:
  tk-substancepainter: "@substancepainter.project"
